# Generated by Django 2.2.7 on 2019-11-24 19:51

import Tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('unique_squirrel_id', models.CharField(max_length=200, validators=[Tracker.models.validate_unique_squirrel_id], verbose_name='Unique Squirrel ID')),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=5, verbose_name='Shift')),
                ('date', models.DateField(validators=[Tracker.models.validate_date], verbose_name='Date')),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=50, verbose_name='Age')),
                ('primary_fur_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=50, verbose_name='Primary Fur Color')),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=50, verbose_name='Location')),
                ('specific_location', models.CharField(blank=True, max_length=200, verbose_name='Specific Location')),
                ('running', models.BooleanField(verbose_name='Running')),
                ('chasing', models.BooleanField(verbose_name='Chasing')),
                ('climbing', models.BooleanField(verbose_name='Climbing')),
                ('eating', models.BooleanField(verbose_name='Eating')),
                ('foraging', models.BooleanField(verbose_name='Foraging')),
                ('other_activities', models.CharField(blank=True, max_length=200, verbose_name='Other Activities')),
                ('kuks', models.BooleanField(verbose_name='Kuks')),
                ('quaas', models.BooleanField(verbose_name='Quaas')),
                ('moans', models.BooleanField(verbose_name='Moans')),
                ('tail_flags', models.BooleanField(verbose_name='Tail flags')),
                ('tail_twitches', models.BooleanField(verbose_name='Tail twitches')),
                ('approaches', models.BooleanField(verbose_name='Approaches')),
                ('indifferent', models.BooleanField(verbose_name='Indifferent')),
                ('runs_from', models.BooleanField(verbose_name='Runs from')),
            ],
        ),
    ]
